package com.badmintontracker.android.localanalysis

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.DataInputStream
import java.io.File
import kotlin.math.abs

/**
 * Measures how far Android's decode and preprocessing land from production's.
 *
 * Design section 5.4 calls this out as a fidelity surface that no gate covers,
 * feeding every model on every frame, and asks for it to be pinned before the
 * device layer is built rather than discovered later as unexplained drift in
 * shuttle positions.
 *
 * Reference generated by tools/models/check_decode_parity.py and pushed to
 * /data/local/tmp/decode-reference.bin alongside the video.
 */
@RunWith(AndroidJUnit4::class)
class FramePreprocessorTest {

    private val NL = System.lineSeparator()

    private class Reference(val width: Int, val height: Int, val frames: Map<Int, ByteArray>)

    private fun reference(): Reference? {
        val f = File("/data/local/tmp/decode-reference.bin")
        if (!f.isFile || !f.canRead()) return null
        DataInputStream(f.inputStream().buffered()).use { s ->
            val magic = ByteArray(4).also { s.readFully(it) }.decodeToString()
            require(magic == "DPAR") { "not a decode reference: $magic" }
            val version = s.readIntLe()
            require(version == 1) { "unsupported reference version $version" }
            val count = s.readIntLe()
            val w = s.readIntLe()
            val h = s.readIntLe()
            val frames = HashMap<Int, ByteArray>(count)
            repeat(count) {
                val idx = s.readIntLe()
                frames[idx] = ByteArray(w * h * 3).also { b -> s.readFully(b) }
            }
            return Reference(w, h, frames)
        }
    }

    private fun DataInputStream.readIntLe(): Int {
        val b = ByteArray(4).also { readFully(it) }
        return (b[0].toInt() and 0xFF) or ((b[1].toInt() and 0xFF) shl 8) or
            ((b[2].toInt() and 0xFF) shl 16) or ((b[3].toInt() and 0xFF) shl 24)
    }

    private fun video(): File? =
        File("/data/local/tmp/corpus-743d7fb1.mp4").takeIf { it.isFile && it.canRead() }

    @Test
    fun the_resize_uses_opencvs_pixel_centre_convention() {
        // A 2x2 upscaled to 4x4. OpenCV maps destination to source as
        // (dst + 0.5) * scale - 0.5, so the outer pixels clamp to the source
        // corners and the inner two interpolate at 0.25 and 0.75. The naive
        // dst * scale form is off by half a source pixel everywhere, which is
        // a sub-pixel shift on every frame feeding every model.
        val src = byteArrayOf(
            0, 0, 0, 100, 100, 100,
            100, 100, 100, 0, 0, 0,
        )
        val dst = ByteArray(4 * 4 * 3)
        FramePreprocessor.resize(src, 2, 2, dst, 4, 4)
        // Expected values taken from cv2.resize on this exact input, not
        // hand-computed. The first version of this test asserted 50 at the
        // centre by reasoning about it; OpenCV gives 38, and the
        // implementation was right. The whole first row is
        // [0, 25, 75, 100] and the second [25, 38, 63, 75].
        fun px(r: Int, c: Int) = dst[(r * 4 + c) * 3].toInt() and 0xFF
        assertEquals(listOf(0, 25, 75, 100), (0..3).map { px(0, it) })
        assertEquals(listOf(25, 38, 63, 75), (0..3).map { px(1, it) })
        assertEquals(listOf(75, 63, 38, 25), (0..3).map { px(2, it) })
        assertEquals(listOf(100, 75, 25, 0), (0..3).map { px(3, it) })
    }

    @Test
    fun the_tensor_is_chw_scaled_by_255() {
        val rgb = byteArrayOf(255.toByte(), 0, 0, 0, 255.toByte(), 0)
        val out = FloatArray(2 * 3)
        FramePreprocessor.toChwTensor(rgb, 2, 1, out)
        // R plane, then G, then B - not interleaved.
        assertEquals(1f, out[0], 1e-6f)
        assertEquals(0f, out[1], 1e-6f)
        assertEquals(0f, out[2], 1e-6f)
        assertEquals(1f, out[3], 1e-6f)
    }

    /**
     * Reports every colour-conversion variant against production, in one
     * decode pass.
     *
     * Diagnostic, not a gate. It exists because the first two attempts here
     * were guesses - BT.601 full range, then BT.709 limited - and a guess that
     * halves the error looks like progress whether or not it is the right
     * answer. Measuring all four at once turns the choice into evidence, and
     * leaves a number behind for whoever next wonders why this constant is
     * what it is.
     */
    @Test
    fun report_every_colour_conversion_against_production() {
        val ref = reference()
        val vid = video()
        assumeTrue("SKIPPED: reference or video absent", ref != null && vid != null)
        val reference = ref!!

        val variants = FramePreprocessor.YuvMatrix.values()
        val rgbFull = ByteArray(1920 * 1080 * 3)
        val resized = ByteArray(reference.width * reference.height * 3)
        val sums = DoubleArray(variants.size)
        val maxes = IntArray(variants.size)
        var compared = 0

        VideoFrameSource(vid!!).forEachFrame { index, _, image ->
            val expected = reference.frames[index] ?: return@forEachFrame
            compared++
            variants.forEachIndexed { vi, matrix ->
                FramePreprocessor.toRgb(image, rgbFull, matrix)
                FramePreprocessor.resize(
                    rgbFull, image.width, image.height, resized, reference.width, reference.height
                )
                var sum = 0L
                for (i in resized.indices) {
                    val d = abs((resized[i].toInt() and 0xFF) - (expected[i].toInt() and 0xFF))
                    sum += d
                    if (d > maxes[vi]) maxes[vi] = d
                }
                sums[vi] += sum.toDouble() / resized.size
            }
        }

        assertTrue("no frames compared", compared > 0)
        val report = variants.mapIndexed { i, m ->
            "  %-16s mean %5.2f/255  max %3d/255".format(m.name, sums[i] / compared, maxes[i])
        }.joinToString(NL)
        println("COLOUR VARIANTS over $compared frames:" + NL + report)
        // Always passes: this measures, it does not judge. The judgement is
        // the threshold test below.
        assertTrue(true)
    }

    @Test
    fun android_decode_matches_production_within_the_threshold() {
        val ref = reference()
        val vid = video()
        assumeTrue(
            "SKIPPED: push decode-reference.bin and corpus-743d7fb1.mp4 to /data/local/tmp",
            ref != null && vid != null,
        )
        val reference = ref!!

        val rgbFull = ByteArray(1920 * 1080 * 3)
        val resized = ByteArray(reference.width * reference.height * 3)
        val stats = ArrayList<Triple<Int, Double, Int>>()

        VideoFrameSource(vid!!).forEachFrame { index, _, image ->
            val expected = reference.frames[index] ?: return@forEachFrame
            // The fused path, which is what the runner uses.
            FramePreprocessor.toRgbResized(image, resized, reference.width, reference.height)
            var sum = 0L
            var worst = 0
            for (i in resized.indices) {
                val d = abs((resized[i].toInt() and 0xFF) - (expected[i].toInt() and 0xFF))
                sum += d
                if (d > worst) worst = d
            }
            stats.add(Triple(index, sum.toDouble() / resized.size, worst))
        }

        assertTrue("no reference frames were compared", stats.isNotEmpty())
        val worstMean = stats.maxOf { it.second }
        val worstMax = stats.maxOf { it.third }
        val report = stats.joinToString("\n") { (i, mean, max) ->
            "  frame %5d  mean %6.2f/255  max %3d/255".format(i, mean, max)
        }
        // Threshold from the plan: a mean absolute difference above 2/255 on
        // any sampled frame means the pipelines disagree materially.
        assertTrue(
            "Android decode differs from production's beyond 2/255.\n" +
                "worst mean ${"%.2f".format(worstMean)}/255, worst max $worstMax/255\n$report",
            worstMean <= 2.0,
        )
    }
}
