#!/usr/bin/env python3
"""Record what production's heatmap postprocessing does, case by case.

Design section 5.4 is emphatic that the shuttle track "is not a heatmap
argmax", and names three stages between the model and a coordinate. The one
that turns a heatmap into an (x, y) is `_heatmap_to_coord`
(`inference.py:477-505`): threshold at 0.5, connected components, reject any
blob larger than `max_area = 100`, take the largest survivor, return its
heatmap-weighted centroid, and report not-visible when nothing survives.

These vectors hold the Kotlin port to that function. `_heatmap_to_coord` is
imported and called here rather than reimplemented - a golden generated by a
second implementation of the thing under test proves only that two people made
the same mistake.

Output, little-endian to match the other formats in this repo:
  heatmaps.bin: magic "SHUT", int32 version, int32 count, then per case
                int32 width, int32 height, width*height float32
  expected.json: {"provenance": {...}, "cases": [{index, name, visible, x, y}]}

Usage:
    python tools/models/make_shuttle_vectors.py [--tracker-repo PATH]
"""
import argparse
import json
import struct
import subprocess
import sys
from pathlib import Path

import numpy as np

OUT = Path("analysis/src/commonTest/resources/shuttle")
MAGIC = b"SHUT"
VERSION = 1


def synthetic_cases():
    """Cases chosen so each one separates the real algorithm from a plausible
    wrong one. An argmax implementation passes case 1 and fails 3, 4 and 5."""
    cases = []

    def blank(w=64, h=48):
        return np.zeros((h, w), dtype=np.float32)

    def disc(hm, cx, cy, r, peak=0.9):
        ys, xs = np.mgrid[0:hm.shape[0], 0:hm.shape[1]]
        m = (xs - cx) ** 2 + (ys - cy) ** 2 <= r * r
        hm[m] = peak
        return int(m.sum())

    # 1. One clean blob, the ordinary case.
    hm = blank(); disc(hm, 20, 15, 3)
    cases.append(("single_clean_blob", hm))

    # 2 and 3. The area filter is `area > max_area`, so 100 is KEPT and 101 is
    # REJECTED. Built as exact-count rectangles rather than discs so the areas
    # are not left to rounding.
    hm = blank(); hm[10:20, 10:20] = 0.9            # exactly 100
    cases.append(("blob_area_exactly_100_is_kept", hm))
    hm = blank(); hm[10:20, 10:20] = 0.9; hm[20, 10] = 0.9   # 101
    cases.append(("blob_area_101_is_rejected", hm))

    # 4. Only an oversized blob. Must be NOT VISIBLE - the single case an
    # argmax implementation can never get right, since argmax always returns a
    # coordinate.
    hm = blank(); hm[5:25, 5:25] = 0.9              # 400
    cases.append(("only_oversized_blob_is_not_visible", hm))

    # 5. Oversized blob plus a small one. The SMALL one must win, so "largest
    # blob" without the area filter fails here.
    hm = blank(); hm[5:25, 5:25] = 0.9; disc(hm, 50, 35, 2)
    cases.append(("small_blob_beats_an_oversized_one", hm))

    # 6. Two valid blobs: the larger wins.
    hm = blank(); disc(hm, 15, 10, 2); disc(hm, 45, 35, 4)
    cases.append(("larger_of_two_valid_blobs_wins", hm))

    # 7. Nothing above threshold.
    cases.append(("empty_heatmap_is_not_visible", blank()))

    # 8. Asymmetric weights inside one blob, so the heatmap-weighted centroid
    # differs measurably from the geometric one. Proves the weighting is
    # applied rather than the blob's centre being returned.
    hm = blank(); hm[20:25, 20:25] = 0.6; hm[20:25, 24] = 1.0
    cases.append(("weighted_centroid_differs_from_geometric", hm))

    # 9. Values just below and just above the 0.5 threshold, so a threshold of
    # 0.4 or 0.6 changes the answer.
    hm = blank(); hm[10:15, 10:15] = 0.49; disc(hm, 40, 30, 2, peak=0.51)
    cases.append(("threshold_is_exactly_half", hm))

    # 10. Two squares touching ONLY at a corner. Under cv2's default
    # 8-connectivity they are one blob of 128, which exceeds max_area and is
    # rejected, so the frame is not visible. Under 4-connectivity they are two
    # blobs of 64, the larger passes the filter, and the frame reports a
    # coordinate. Visible versus not-visible, from connectivity alone.
    #
    # Added after mutation testing: flipping the Kotlin to 4-connected passed
    # every other case here, so the suite was asserting a property of the
    # implementation that nothing actually checked.
    hm = blank()
    hm[10:18, 10:18] = 0.9
    hm[18:26, 18:26] = 0.9
    cases.append(("diagonal_touch_is_one_blob_under_8_connectivity", hm))

    return cases


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tracker-repo", default="../badminton-tracker")
    args = ap.parse_args()

    tracker = Path(args.tracker_repo).resolve()
    sys.path.insert(0, str(tracker / "backend"))
    from tracknet.inference import TrackNetInference

    coord = TrackNetInference._heatmap_to_coord

    dirty = subprocess.run(
        ["git", "-C", str(tracker), "status", "--porcelain", "--", "backend"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    if dirty:
        print(f"REFUSING: badminton-tracker/backend is dirty:\n{dirty}", file=sys.stderr)
        return 2
    sha = subprocess.run(
        ["git", "-C", str(tracker), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()

    cases = synthetic_cases()
    OUT.mkdir(parents=True, exist_ok=True)
    with (OUT / "heatmaps.bin").open("wb") as f:
        f.write(MAGIC)
        f.write(struct.pack("<ii", VERSION, len(cases)))
        for _, hm in cases:
            f.write(struct.pack("<ii", hm.shape[1], hm.shape[0]))
            f.write(hm.astype(np.float32).tobytes())

    expected = []
    for i, (name, hm) in enumerate(cases):
        r = coord(hm)
        expected.append({
            "index": i, "name": name,
            "visible": bool(r["visible"]), "x": float(r["x"]), "y": float(r["y"]),
        })
        print(f"  {name:44} visible={str(r['visible']):5} x={r['x']:8.4f} y={r['y']:8.4f}")

    (OUT / "expected.json").write_text(json.dumps({
        "provenance": {
            "tracker_commit": sha,
            "function": "tracknet.inference.TrackNetInference._heatmap_to_coord",
            "generated_by": "tools/models/make_shuttle_vectors.py",
        },
        "cases": expected,
    }, indent=1))
    print(f"\nwrote {OUT}/heatmaps.bin and expected.json ({len(cases)} cases)")
    print(f"badminton-tracker commit: {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
